### ISSUE TITLE
Async?

### ISSUE THREAD

**Issue by alphapapa** [jgkamat/matrix-client-legacy-el#1]
Hi,

Thanks for forking this.  It seems pretty nice so far.

Seems like one of the first issues is that sending messages is synchronous, so after hitting `RET` to send a message, Emacs is blocked until the server accepts it.

I wonder if the `async` and/or `deferred` libraries could be used for this.  What do you think?

Thanks.

**Comment by jgkamat** [comment]
I think that this is definetly possible, and it would improve the experience a lot. I've actually been having many, many other bugs with this, so I'm not sure if I'll be able to get to this, but I'll happily accept contributions to try to improve it :)

(I'm just as unfamiliar with the codebase as anyone else, so we'll see how this goes...)

**Comment by alphapapa** [comment]
Thanks.  I've never written async code in Emacs before, and I don't think I have the time to spend on it, so I'll wait patiently for now.  :)  Let me know if you need me to test anything you may come up with!

**Comment by alphapapa** [comment]
BTW I see now that there is some async code in the package.  I haven't followed the chain of what happens when sending messages, but maybe the issue isn't quite so straightforward.

**Comment by alphapapa** [comment]
Now that I've looked through the code, I see that sending a message calls `matrix-send`, which is synchronous, rather than `matrix-send-async`.  There's probably a reason for that, but we can look into doing it async instead.

**Comment by alphapapa** [comment]
Now that I understand a bit more about how async works in the package, and we've made message sending async, I'm going to close this.  We should generally try to use async whenever possible.
