### ISSUE TITLE
Replace add-to-list with...?

### ISSUE THREAD

**Issue by alphapapa** [jgkamat/matrix-client-legacy-el#4]
Hi Jay,

I noticed that `add-to-list` is used to add to alists.  The Elisp docs recommend against this.  For example:

```el
(defmethod matrix-login ((con matrix-connection) login-type arg-list)
  "Attempt to log in to the Matrix homeserver.

LOGIN-TYPE is the value for the `type' key.
ARG-LIST is an alist of additional key/values to add to the submitted JSON."
  (let ((resp (matrix-send con "POST" "/login" (add-to-list 'arg-list (cons "type" login-type)))))
    (oset con :token (cdr (assoc 'access_token resp)))
    resp))
```
What do you think about replacing these calls?  There are several options that I know of.

These are non-destructive:

* `cl-acons`
* `a-assoc` from a.el (the examples make it appear destructive, but the code appears non-destructive)

These are destructive:

* `push`/`cl-pushnew` with `cons`
* `asoc-put!` from asoc.el

I think, for convenience's sake, I would suggest `asoc-put!`, as it would make the code cleaner, and the asoc.el library seems pretty nice.  a.el is also very nice, but lacks a destructive setter; it would be nice to avoid having to use `setq` when appropriate.

**Comment by alphapapa** [comment]
I just realized that asoc.el is not in MELPA yet.  And there's also a similar alternative in Emacs now: `map-put`.  It is destructive (a macro around `setf`), so I recommend we use that.

**Comment by jgkamat** [comment]
I agree with avoiding `asoc.el`, since it is probably a bit hard to get people install it just for this.`

I had never heard of `map-put` before, but it definetly sounds like the best option, nice job finding that (I'll probably be using it myself from now on). `cl-pushnew` would have been my second choice if `map-put` didn't exist.

**Comment by alphapapa** [comment]
Yeah, map.el is new in Emacs, very nice library by Nicolas Petton.

I've done some cleanups in `matrix-api.el`.  I'll send a PR for you to review...

**Comment by alphapapa** [comment]
Actually I'll leave this open, since I haven't made this change all over the codebase yet.

**Comment by alphapapa** [comment]
I think this can be closed now.
